markdown: rdiscount
permalink: /:title/
url: http://xblinux.github.io
name: XB Linux
author: xblinux
qq: 277357787
email: xblinux@yeah.net
duoshuo: 
beian: 
cnzz: 
weibo: 
github: xblinux
pygments: true
safe: true
paginate: 20
about: 这里是XB Linux的博客