markdown: rdiscount
permalink: /:title/
url: http://okcarpediem.github.io
name: okcarpediem
author: okcarpediem
qq: 277357787
email: paul34@163.com
duoshuo: 
beian: 
cnzz: 
weibo: 
github: okcarpediem
pygments: true
safe: true
paginate: 20
about: 这里是okcarpediem的博客