markdown: rdiscount
permalink: /:title/
url: http://okcarpediem.github.io
name: XB Linux
author: okcarpediem
qq: 277357787
email: xblinux@163.com
duoshuo: yonsm
beian: 
cnzz: 119959
weibo: 
github: okcarpediem
pygments: true
safe: true
paginate: 20
about: 这里是XB Linux的博客